version: '3'

volumes:
  mongo-datastore:

services: 
  frontend:
    build:
      context: ./frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    expose:
      - 3000
    ports:
    - "3000:3000" # For debug purpose only
    depends_on:
      - mongo
    environment:
      HASHING_KEY: ${BACKEND_HASHING_KEY}
      JWT_SIGN_SECRET: ${JWT_SIGN_SECRET}
      VAPID_PUBLIC_KEY: ${VAPID_PUBLIC_KEY}
      VAPID_PRIVATE_KEY: ${VAPID_PRIVATE_KEY}

  mongo:
    build: ./mongo
    volumes: 
      - mongo-datastore:/data/db
    expose:
      - 27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASS}
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}